### ISSUE TITLE
Which banks are compatible?

### ISSUE THREAD

**Issue by lakano** [OpenPSD/psd2-server#1]
Hi!
We would like to connect to banks accounts of our users through the PSD2 API, but we don't found any documentation to do it correctly for all banks.
What is the purpose of your PSD2 server please ? Is it for bank companies to support PSD2 API ? Or is it a small service to run on our side to permit us to use the PSD2 API of banks ?
If yes, is it compatible with every European banks please?
Thanks for your help!

**Comment by mobinauten** [comment]
The main intension is to providing a test server for banks that implement the PSD2 BerlinGroup API spec. which are probably and hopefully the most in EU Europe in the end. 
So one can download the server and test, if an app works PSD2 BG API spec. with SCA and data compliant. 

In a later stage the server could also be leveraged to connect directly with a bank using real world UAT or PROD instances. 

Does that help? 
Cheers 
Oliver

**Comment by lakano** [comment]
Ok I understood, thanks for your answer!
We searching a client side code, to connect to all banks that support PSD2, but we don't found anything yet!
Regards,
